Add Igloo support for second device
jreese/znc-push pull request #259
Opened 2021-05-04 01:43 UTC by mcrute

The Igloo push service supports simultaneous push to multiple devices. This patch allows for a second device.

2021-05-04 17:49 UTC, eskimo commented
@jreese This is the last thing needed to be merged before I can take down my fork. It's a must have for many Igloo users.

2021-05-06 04:24 UTC, jreese requested changes
Is there a case where Igloo would ever support a third device?  Would it be better to just support multiple devices in the "target" field by splitting on spaces and/or commas?

2021-05-06 04:24 UTC, jreese commented on push.cpp
> +			// network is special because it can be nullptr if the user has none set up yet
Duplicate line?

2021-05-06 04:29 UTC, eskimo commented
> Is there a case where Igloo would ever support a third device? Would it be better to just support multiple devices in the "target" field by splitting on spaces and/or commas?

I actually supported up to 5 devices previously and based on my push logs I found that nobody ever used more than 2, so 2 is fine. 

I think 2 params is better given the length of the tokens, would be a hassle to have to get, then copy paste, then paste the next one and then set imo.

2021-05-06 04:55 UTC, jreese approved these changes

2021-05-06 04:57 UTC, merged